# Generated by Django 2.2 on 2020-08-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
