# Generated by Django 2.2 on 2020-08-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200817_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_added',
        ),
    ]
